# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["chris@nunciato.org"]
cloned_from = "https://github.com/fastly/compute-starter-kit-typescript"
description = "My new app"
language = "javascript"
manifest_version = 3
name = "app"

[scripts]
build = "npm run build"
post_init = "npm install"
